import React from "react"
import Head from "next/head";
import type { NextPage } from 'next'
import Link from "next/link";
import Image from "next/image";
import createClient from "../../services/client/client";
import { useCookies } from "react-cookie";
import Button from "react-bootstrap/Button";
import { LABEL, ADD_LABEL_TO_FAVORITES, REMOVE_LABEL_FROM_FAVORITES } from "../../services/client/queries";
import Col from "react-bootstrap/Col";
import Layout from "../../src/components/layout";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { requireAuthentication } from "../../services/auth/requireAuthentication";
import { FaStar } from "react-icons/fa";
import { FaTrash } from "react-icons/fa";
import { LabelObject, CTX } from "../../types"
import { useNotificationContext } from "../../src/context/notification/context";


const Label: NextPage<LabelObject> = (props: LabelObject) => {
  const { data } = props;
  const [isFavorite, setIsFavorite] = React.useState(true);
  const { name, profile, contact_info, urls, images, id } = data.label;
  const [cookies] = useCookies<any>(["auth"]);
  const { dispatch }: any = useNotificationContext();

  React.useEffect(() => {
    setFavoriteState()
  }, [])


  async function setFavoriteState(): Promise<void> {
    let Ids: number[] = [];
    await data.getFavoritesLabel.map((id: any) => {
      Ids.push(parseInt(id.label_id))
    });
    setIsFavorite(Ids.includes(id));
  }

  async function addToFavorites(id: number, name: string): Promise<void> {
    const token = cookies.token;
    const client = createClient(token);
    const { errors } = await client.mutate({
      mutation: ADD_LABEL_TO_FAVORITES,
      variables: {
        label_id: id,
        label_name: name,
      },
    });
    if (errors) {
      dispatch({ type: "notification", payload: { text: errors[0].message, type: "danger" } })
    } else {
      setIsFavorite(true);
      dispatch({ type: "notification", payload: { text: "success", type: "success" } })
    }
  }
  async function removeElemFromFavorites(data: any) {
    const token = cookies.token;
    const client = createClient(token);
    const { errors } = await client.mutate({
      mutation: REMOVE_LABEL_FROM_FAVORITES,
      variables: data,
    });
    if (errors) {
      dispatch({ type: "notification", payload: { text: errors[0].message, type: "danger" } })
    } else {
      setIsFavorite(false);
      dispatch({ type: "notification", payload: { text: "success", type: "success" } })
    }
  }

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Col md={8}>
        <h1>{name}</h1>
        {!isFavorite ? (
          <Button
            variant="warning"
            onClick={() => addToFavorites(id, name)}
          >
            <FaStar />
          </Button>
        ) : (
          <Button
            variant="danger"
            onClick={() => removeElemFromFavorites(data.label)}
          >
            <FaTrash />
          </Button>
        )}

        <Link href={`/label_releases/${id}`}>Releases</Link>
        <p>{profile}</p>
        <p>{contact_info}</p>
        {!!images && images.length > 0
          ? images.map((img) => {
            return !!img.resource_url ? (
              <Image
                src={img.resource_url}
                layout="responsive"
                width="500px"
                height="500px"
              />
            ) : null;
          })
          : null}
        <ul>
          {!!urls
            ? urls.map((url) => (
              <li>
                <Link href={url}>{url}</Link>
              </li>
            ))
            : null}
        </ul>
      </Col>
    </Layout>
  );
}
export default Label
export const getServerSideProps = requireAuthentication(async (context: CTX) => {
  const slug = context.query.slug;
  const locale = context.locale
  const token = JSON.parse(JSON.stringify(context.req.cookies)).token || "";

  const client = createClient(token);
  const { data, errors } = await client.query({
    query: LABEL,
    variables: {
      slug: slug,
    },
  });
  let errorCode = errors ? errors : false;
  if (errorCode) {
    context.res.statusCode = 404;
  }

  return { props: { errorCode, data, ...await serverSideTranslations(locale, ['common']) } };

})
