import React from "react"
import Head from "next/head";
import Col from "react-bootstrap/Col";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { CTX } from "../types";
import { useTranslation } from "next-i18next";
import { useRouter } from 'next/router'

export default function ErrorPage() {
  const router = useRouter()
  const { t } = useTranslation("common");
  React.useEffect(() => {
    setTimeout(() => {
      router.back()
    }, 3000)
  }, [])
  return (
    <>
      <Head>
        <title>{t("404")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Col md={8}>
        <h1>{t("404")}</h1>

      </Col>
    </>
  );
}

export const getStaticProps: any = (
  async (context: CTX) => {
    const locale: string = context.locale;
    return { props: { ...await serverSideTranslations(locale, ['common']) } };
  }
);

