import Head from "next/head";
import Col from "react-bootstrap/Col";
import Layout from "../src/components/layout";


export default function ErrorPage() {


  return (
    <Layout>
      <Head>
        <title>500 - Page Not Found!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Col md={8}>
        <h1>500 - Page Not Found!</h1>

      </Col>
    </Layout>
  );
}


