import React from "react";
import Head from "next/head";
import Col from "react-bootstrap/Col";
import Layout from "../src/components/layout";
import { useNotificationContext } from "../src/context/notification/context";
const CustomError = ({ statusCode }: any) => {
  const { dispatch }: any = useNotificationContext();
  React.useEffect(() => {
    dispatch({
      type: "notification",
      payload: { text: statusCode, type: "danger" },
    });
  }, []);

  return (
    <Layout>
      <Head>
        <title>
          {statusCode
            ? `An error ${statusCode} occurred on server`
            : "An error occurred on client"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Col md={8}>
        <h1>
          {statusCode
            ? `An error ${statusCode} occurred on server`
            : "An error occurred on client"}
        </h1>
      </Col>
    </Layout>
  );
};

function getInitialProps({ res, err }: any) {
  let statusCode;
  // If the res variable is defined it means nextjs
  // is in server side
  if (res) {
    statusCode = res.statusCode;
  } else if (err) {
    // if there is any error in the app it should
    // return the status code from here
    statusCode = err.statusCode;
  } else {
    // Something really bad/weird happen and status code
    // cannot be determined.
    statusCode = null;
  }
  return { statusCode };
}

CustomError.getInitialProps = getInitialProps;

export default CustomError;
