import React from "react";
import Head from "next/head";
import Table from "react-bootstrap/Table";
import Layout from "../src/components/layout";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { requireAuthentication } from "../services/auth/requireAuthentication";
import createClient from "../services/client/client";
import { USERS } from "../services/client/queries";
import { CTX } from "../types"
import { useTranslation } from "next-i18next";
const Users: any = (props: any) => {
  const { data } = props
  const { users } = data
  const { t } = useTranslation("common");
  return (
    <Layout>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table striped bordered hover variant="dark">
        <thead>
          <tr>
            <th>{t("user_name")}</th>
            <th>{t("first_name")}</th>
            <th>{t("last_name")}</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user: any) => {
            return (
              <tr style={{ cursor: "pointer" }} onClick={() => alert(user.email)}>
                <td >{user.user_name}</td>
                <td>{user.first_name}</td>
                <td>{user.last_name}</td>
                <td>{user.email}</td>
              </tr>
            )
          })}
        </tbody>
      </Table>
    </Layout>
  );
}


export default Users
export const getServerSideProps = requireAuthentication(async (context: CTX) => {
  const locale = context.locale
  const token = JSON.parse(JSON.stringify(context.req.cookies)).token || "";

  const client = createClient(token);
  const { data, errors } = await client.query({
    query: USERS
  });
  let errorCode = errors ? errors : false;
  if (errorCode) {
    context.res.statusCode = 404;
  }

  return { props: { errorCode, data, ...await serverSideTranslations(locale, ['common']) } };

})
